website/models.py
from . import db
import re
from time import time

from unidecode import unidecode

# from flask_security import UserMixin, RoleMixin

from sqlalchemy.sql import func

# from sqlalchemy import event


# Function that processes title of a post and returns a slug.
def slugify(post_title):
    pattern = r'[^\w+]'
    title = unidecode(post_title)
    return str.lower(re.sub(pattern, '-', title))


# Create table in database for storing posts
class Question(db.Model):
    __tablename__ = 'question'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    content = db.Column(db.Text)
    created_at = db.Column(db.DateTime(timezone=True), default=func.now())
    edited_at = db.Column(db.DateTime(timezone=True), default=func.now())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
        else:
            self.slug = str(int(time()))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
# from os import path
# from flask_login import LoginManager, login_manager, login_user
# from flask_security import Security, SQLAlchemySessionUserDatastore
from flask_migrate import Migrate
from flask_ckeditor import CKEditor

db = SQLAlchemy()
ckeditor = CKEditor()


def create_app():
    app = Flask(__name__)
    app.config.from_object("config.DevelopmentConfig")
    ckeditor.init_app(app)
    db.init_app(app)

    migrate = Migrate(app, db, render_as_batch=True)

    from .views import views
    # from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    # app.register_blueprint(auth, url_prefix="/")

    from . import models

    with app.app_context():
        db.create_all()
        print("Created Database!")

    # l_manager = LoginManager()
    # l_manager.login_view = "auth.login"
    # l_manager.init_app(app)

    # @l_manager.user_loader
    # def load_user(user_id):
    #     return models.User.query.get(int(user_id))
    #
    # user_datastore = SQLAlchemySessionUserDatastore(db.session, models.User, models.Role)
    # security = Security(app, user_datastore)

    return app

website/views.py
from flask import Blueprint, render_template, request, flash, current_app, redirect, url_for
# from flask_login import login_required, current_user
# from flask_security import roles_required
# from werkzeug.utils import secure_filename
# from datetime import datetime, date
import time
import os
import random
from . import db
from .models import Question, slugify

views = Blueprint("views", __name__)

ROWS_PER_PAGE = 10

# def time_convert(sec):
#     mins = sec // 60
#     sec = sec % 60
#     hours = mins // 60
#     mins = mins % 60
#     print("Time Lapsed = {0}:{1}:{2}".format(int(hours), int(mins), sec))


@views.errorhandler(404)
def not_found(e):
    return render_template('404.html')


@views.route('/')
def home():
    return render_template("home.html")


# Query and display 3 random questions from database
@views.route('/questions', methods=['GET', 'POST'])
def query_questions():
    global questions
    global query_result
    query = Question.query.all()

    if 'quit' in request.form:
        return render_template('home.html')

    elif request.form and query_result:
        for x in query_result:
            questions.remove(x)

    elif 'next' in request.form or not request.form:
        if not request.form:
            questions = query

    try:
        quiz = random.sample(questions, 3)
    except ValueError:
        flash('W bazie danych jest za mało pytań', category='error')
        return redirect(url_for('views.home'))
    query_result = quiz
    return render_template('questions/query_questions.html', questions=quiz)

    # input("Press Enter to start")
    # start_time = time.time()
    # input("Press Enter to stop")
    # end_time = time.time()
    # time_lapsed = end_time - start_time
    # time_convert(time_lapsed)


@views.route('/create-question', methods=['GET', 'POST'])
def create_question():
    if request.method == 'POST':
        title = request.form.get("title")
        # content = request.form.get("content")
        content = request.form.get("ckeditor")
        if not title or not content:
            flash('Please fill in all the fields.', category='error')
        else:
            new_phrase = Question(title=title, content=content)
            db.session.add(new_phrase)
            db.session.commit()
            flash('Phrase created!', category='success')
            # return redirect(url_for('views.admin_console'))
    return render_template('questions/create_question.html')


@views.route('/edit-question/<slug>', methods=['GET', 'POST'])
def edit_question(slug):

    question = Question.query.filter(Question.slug == slug).first()

    if request.method == 'POST':
        title = request.form.get("title")
        content = request.form.get("ckeditor")

        if question.title != title:
            question.title = title
            question.slug = slugify(title)

        question.content = content
        db.session.add(question)
        db.session.commit()

        flash('Zmiany zostały zapisane!', category='success')
        return redirect(url_for('views.show_all_questions'))

    return render_template('questions/edit_question.html', question=question)


@views.route('/show-question/<slug>')
def show_question(slug):
    question = Question.query.filter(Question.slug == slug).first()
    return render_template('questions/show_question.html', question=question)


@views.route('/show-all-questions')
def show_all_questions():
    page = request.args.get('page', 1, type=int)
    questions = Question.query.paginate(page=page, per_page=ROWS_PER_PAGE)

    return render_template('questions/show_questions.html', questions=questions)


@views.route('/delete-question/<slug>')
def delete_question(slug):
    pass

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="https://kit.fontawesome.com/eb6e6a7399.js" crossorigin="anonymous"></script>


    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
        <div class="container-fluid">
            <a href="{{ url_for('views.home') }}" class="navbar-brand">Fiszki na egzamin</a>
{#            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"#}
{#                    data-bs-target="#navbarSupportedContent"#}
{#                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#                <span class="navbar-toggler-icon"></span>#}
{#            </button>#}
{#            <div class="collapse navbar-collapse flex-row-reverse" id="navbarSupportedContent">#}
{#                <div class="navbar-nav my-2 my-lg-0">#}
{#                    <a class="nav-item nav-link"#}
{#                       href="{{ url_for('views.show_post', slug=menu_trick_post.slug, category=menu_trick_category.name) }}">O#}
{#                        TRICKACH</a>#}
{#                    <a class="nav-item nav-link"#}
{#                       href="{{ url_for('views.show_post', slug=menu_about_post.slug, category=menu_about_category.name) }}">O#}
{#                        STRONIE</a>#}
{#                </div>#}
{#            </div>#}
        </div>
    </nav>
</header>

{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            {% elif category == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}

<main>
    {% block content %}{% endblock %}
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"
></script>
<script src="{{ url_for('static', filename='js/app.js') }}"></script>

</body>
</html>

website/templates/home.html
{% extends "base.html" %}
{% block title %}Fiszki na egzamin{% endblock %}
{% block content %}
    <div class="fiszki-container">
        <h1>Fiszki na egzamin</h1>
        <div class="pt-4 d-flex flex-column flex-md-row justify-content-evenly">
            <a class="btn btn-lg btn-success" href="{{ url_for('views.query_questions') }}">Losuj 3 pytania</a>
            <a class="btn btn-lg btn-secondary" href="{{ url_for('views.create_question') }}">Dodaj pytanie</a>
            <a class="btn btn-lg btn-secondary" href="{{ url_for('views.show_all_questions') }}">Pokaż listę pytań</a>
        </div>
    </div>
{% endblock %}

website/templates/questions/create_question.html
{% extends "base.html" %}
{% block title %}Dodaj nowe pytanie{% endblock %}
{% block content %}
    {{ ckeditor.load() }}
    <div class="container">
        <h1 align="center">Dodaj nowe pytanie</h1>

        <form method="POST" enctype="multipart/form-data">

            <label for="title" class="form-label">Treść pytania</label>
            <input type="text" id="title" name="title" class="form-control mb-4" placeholder="Wpisz treść pytania">

            <label for="content" class="form-label">Odpowiedź na pytanie</label>
            {{ ckeditor.create() }}
{#            <textarea name="content" id="content" class="form-control mb-4"></textarea>#}

            <div class="mt-4">
                <button type="submit" class="btn btn-lg btn-primary">Dodaj</button>
            </div>
        </form>
    </div>
{% endblock %}

website/templates/questions/edit_question.html
{% extends "base.html" %}
{% block title %}Edytuj pytanie{% endblock %}
{% block content %}
    {{ ckeditor.load() }}
    <div class="container">
        <h1 align="center">EDYTUJ PYTANIE - {{ question.title }}</h1>

        <form method="POST" enctype="multipart/form-data">

            <label for="title" class="form-label">Treść pytania</label>
            <input type="text" id="title" name="title" class="form-control mb-4" value="{{ question.title }}">

            <label for="content" class="form-label">Odpowiedź na pytanie</label>
            {{ ckeditor.create(value=question.content) }}
{#            <textarea name="content" id="content" class="form-control mb-4"></textarea>#}

            <div class="mt-4">
                <button type="submit" class="btn btn-lg btn-primary">Dodaj</button>
            </div>
        </form>
    </div>
{% endblock %}

website/templates/questions/query_questions.html
{% extends "base.html" %}
{% block title %}Wylosowane pytania{% endblock %}
{% block content %}
    <div class="container-fluid">
        <h1>Wylosowane pytania</h1>
        {% for question in questions %}
        <div class="accordion mb-4" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="{{ 'heading' + question.id|string }}">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#{{ 'collapse' + question.id|string }}" aria-expanded="true" aria-controls="{{ 'collapse' + question.id|string }}">
                        {{ question.title }}
                    </button>
                </h2>
                <div id="{{ 'collapse' + question.id|string }}" class="accordion-collapse collapse" aria-labelledby="{{ 'heading' + question.id|string }}"
                     data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        {{ question.content|safe }}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <form method="POST" action="{{ url_for('views.query_questions') }}">
            <button name="next" type="submit" class="btn btn-lg btn-primary">Losuj kolejne pytania</button>
            <button name="quit" type="submit" class="btn btn-lg btn-primary">Wróć do menu</button>
        </form>
    </div>
{% endblock %}

website/templates/questions/show_question.html
{% extends "base.html" %}
{% block title %}{{ question.title }}{% endblock %}
{% block content %}
    <div class="container-fluid">
        <h1>{{ question.title }}</h1>
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="{{ 'heading' + question.id|string }}">
                    <button class="accordion-button collapsed fw-bold" type="button" data-bs-toggle="collapse"
                            data-bs-target="#{{ 'collapse' + question.id|string }}" aria-expanded="true" aria-controls="{{ 'collapse' + question.id|string }}">

                    </button>
                </h2>
                <div id="{{ 'collapse' + question.id|string }}" class="accordion-collapse collapse show" aria-labelledby="{{ 'heading' + question.id|string }}"
                     data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        {{ question.content|safe }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/questions/show_questions.html
{% extends "base.html" %}
{% block title %}Wszystkie pytania{% endblock %}
{% block content %}
    <div class="container">
        <div class="container-fluid d-inline-flex justify-content-between mb-4">
            <h1>Wszystkie tricki</h1>
            <a class="btn btn-success" href="{{ url_for('views.create_question') }}">Dodaj nowe pytanie</a>
        </div>
        <ol class="list-group list-group-numbered">
            {% for question in questions %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold pb-2">{{ question.title }}</div>

                        <a class="btn btn-success btn-sm"
                           href="{{ url_for('views.show_question', slug=question.slug) }}">Pokaż pytanie</a>

                        <a class="ms-4 btn btn-primary btn-sm"
                           href="{{ url_for('views.edit_question', slug=question.slug) }}">Edytuj pytanie</a>

                        <form method="POST" class="ps-4 d-inline-flex"
                              action="{{ url_for('views.delete_question', slug=question.slug) }}">
                            <input disabled type="submit" class="btn btn-outline-secondary btn-sm" value="Usuń"
                                   onclick="return confirm('Czy na pewno chcesz usunąć to pytanie?')">
                        </form>

                    </div>
                    {#                    <span class="badge bg-primary rounded-pill">14</span>#}
                </li>
            {% endfor %}
        </ol>

        <!-- Pagination Links-->
        <div class="text-right mt-4">
            <a href="{{ url_for('views.show_all_questions', page=questions.prev_num) }}"
               class="btn btn-outline-dark
       {% if questions.page == 1 %}disabled{% endif %}">
                &laquo;
            </a>
            <!-- Loop through the number of pages to display a link for each-->
            {% for page_num in questions.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    <!-- Check for the active page and set the link to "Active"-->
                    {% if questions.page == page_num %}
                        <a href="{{ url_for('views.show_all_questions', page=page_num) }}"
                           class="btn btn-dark">
                            {{ page_num }}
                        </a>
                    {% else %}
                        <a href="{{ url_for('views.show_all_questions', page=page_num) }}"
                           class="btn btn-outline-dark">
                            {{ page_num }}
                        </a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
            <a href="{{ url_for('views.show_all_questions', page=questions.next_num) }}"
               class="btn btn-outline-dark
       {% if questions.page == questions.pages %}disabled{% endif %}">
                &raquo;
            </a>
        </div>
    </div>
{% endblock %}